### ISSUE TITLE
[Research] Review Grafana metrics

### ISSUE THREAD

**Issue by jiekang** [rh-jmc-team/jfr-datasource#36]
Not all JFR metrics can be visualized in Grafana using the Simple JSON data source. The list of metrics should be reviewed and pruned appropriately.

**Comment by andrewazores** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Determine Grafana supported events](https://trello.com/c/76VoM8AW/1-determine-grafana-supported-events)

**Comment by jiekang** [comment]
@andrewazores Hmm curious. Was the comment automated from Trello?

**Comment by andrewazores** [comment]
I think so. IIRC if you go to Trello and attach the issue with the GitHub "powerup", then it automates that comment so you have a two-way link?

**Comment by jiekang** [comment]
Would disabling that be on a per-user basis? It doesn't make too much sense if a Trello board is private.

**Comment by andrewazores** [comment]
I think I just disabled it on the powerup settings.

**Comment by jiekang** [comment]
Neat, thanks!
