### ISSUE TITLE
[Task] Investigate possibility to eliminate Simple JSON Datasource adapter

### ISSUE THREAD

**Issue by tabjy** [rh-jmc-team/jfr-datasource#42]
Rather than using Simple JSON Datasource as an adapter, we should explore the possibility of implementing Grafana native data source plugin. 

But first, we need to determine how much this project will benefit from being a native plugin.

**Comment by jiekang** [comment]
After investigation, it was concluded that it wouldn't be worth the effort, at least for now. Thanks @tabjy!
